using System.ComponentModel.DataAnnotations;

namespace Picklr.Models
{
    // Named PicklProgram to avoid a name collision with the top-level Program class
    // generated by .NET's top-level statements feature.
    public class PicklProgram
    {
        [Key]
        public int ProgramID { get; set; }

        [Required(ErrorMessage = "Please enter a program name.")]
        public string Name { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        [Range(0, 10000, ErrorMessage = "Fee must be between 0 and 10000.")]
        public decimal Fee { get; set; }

        // FK to Club
        public int ClubID { get; set; }
        public Club? Club { get; set; }

        // Bit-flag weekday availability
        public Weekdays AvailableDays { get; set; }
    }
}
